debug: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
